<?php include "db.php"; ?>

<?php
global $connection;

$query = "SELECT * FROM audi";
$result = mysqli_query($connection, $query);

//Ha üresek a táblák, töltse fel teszt adatokkal
if(mysqli_num_rows($result) == 0)
{

    $query = "INSERT INTO citroen 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('C-ELYSEE', 'A Citroën C-Elysée orr-része teljesen megújul! A hűtőrács és a fényszórók egységet képeznek, ezzel erősítve a tekintélyes megjelenést és a szedán innovatív dizájnját. A 4-ajtós modell színskálája két új modern árnyalattal bővült: az egyik a Lazuli kék, a másik pedig az Artense szürke. Dizájn, kényelem, megjelenés, technológia… Tekintse meg videóinkat és ismerje meg a megújult Citroën C-Elyséet!', 'Citroëns C-Elysée nose section is completely revamped! The grille and headlights are united, enhancing the prestigious look and innovative design of the sedan. Lazuli in blue and Artense in gray. Design, comfort, appearance, technology… Watch our videos and get to know the new Citroën C-Elysée!', 'img/citroen/C-Elysee.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2U63R3NDAEH5C57QCIKQXLTLCVNFX3YAXUNQDGBPCZMQ5VCEWEH7X3RSITPD5S7I3TUZZOMRXSFSSTHSBC5NCQNCENXECWOLAE2HYYFCSQUPC3GQHWSIAO2JGASM5Z4JV4FL6I2UMDA52QIHU4J4ZPGZJJDD3CAK7LDSFHEUMCVRM3QGHSPMUXANMV2Z3TUTWIUFZX23TKQDCOVRW6G3RKRZERLCBZJDJYGBXUVTAKVMZBW6UEAMXEK445OO5DIVYMOSRKNDXJJ7OCFXBA2JAFV37MBI536W6TITK3GNRIUHEX4E6P4L6QMFUE2D5KPVK3JXYMQH5LWH7IV7RSYYYKKALL5BKL2RIU7OSPY4MOGVNDGEJMG67WQRRUTRJBKPONW42CWPNAA5G4E7DGYNZVGLMIOWVNK2OYU6RA2VZ6CQMLKHNHJJUOZFJLFX4URQH54AE2XQBRWATWRDRAW4ZOTRVT2JRJRF4BMPFHM5XUJOSNOY55RO3G55DZVJXTMCQ6MU5ANPJLP72JT45ZNXZAMXRT5EFM7BIC5LTZNIGAN7KLOBHT6YUDWUSJ7Z5T5BZRU773EEEHD4HHYWM4VGCB5M355GS74A6KKUUCF7UWECAWRWQUCHJ6LEEBLHANMVBKTBLK7C7J4WGDP3GNWKYLFDLIV5E46UXGDHQHQZ5VI4XYCH3J32JXXNDLOEO7SOQSU6TIWIN56HCHUB4GFKBP4QNDGNCQO4NZ7HY76I7PWGOHZSH75G67LKFC7J2RPZ7OEFOB5A', 'https://www.citroen.hu/modellek/citroen/C-Elysee.html')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO citroen 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('C3', 'Új szelek fújnak a kompakt városi autók kategóriájában! Az Citroën C3 legmeghatározóbb elemei : optimista és letisztult designja, szépen megrajzolt ívei, a többféle színben játszó  Airbump® és olyan technológiák, mint például a  Citroën ConnectedCAM™. Kifejező és egyedi kialakítása összetéveszthetetlenné teszi az új modellt.', 'New winds blowing in the compact city car category! and clean design, beautifully drawn arcs, Airbump® in multiple colors and technologies like Citroën ConnectedCAM ™. Its expressive and unique design makes the new model unmistakable.', 'img/citroen/c3.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UDAFE3N2R4W2V5JFX4AKNS2ATRPSMMQN3ISMUP7PTDUAUWN4WE5GOLTHFYDGIVKJPOIELKIFA2EJ36IFA4OEIHVRYKFHBQYLM2FP2JAR3JFICJTXHRGHRSPZA2RQMAM2BA3TCP6KJWOOJYCYACX234VJJFDIUMLG4BZ4S3FEYDPNPWO4MGKZCQU66W42VA4TNMZ7QWYP7GSCRRTPTOKJ26DQD4FAYCVPDRFFJKMYOIXTQLTZYQHWNBER33IE7TXJR6OCHHDB2ZCD3NFMSJT7CN5BTGVR4WFCU6S7QL47SZWDD5BGQZKIGVMVTOY5RT7VTD7YKX2OUFGFS4A25JKUZMOVF2MW6DGTQNDMZRGFITTOIOBCFJFZ6TTI2ZVUCAP3QT4OFYKPEZNRQS2V5LIDCT2ECLND4G4YWVO6OSRIVSKUW3PZ43AN3IKLVOADD4BBFD3CB53SF2TOXGVXEDSLCWLFWJF4TLUS3XGXMNWZLPE6NVU75RYBRTTIHL2D376W47HGLJ6JTH4E2JHLXYLYWKY67KBQDP2T3QJ46WFAXWI454SZ6W7I4P55FMFRCZQD3LGM5FGCJXZUT2NF7ZBYUFJIKWPUXMDASQGWU2GJ2KUGD2FABNFDKTCPM7S5JEXGCPLMNWKYHFDLIF5EU6VTBPQNOQB3V2PSK5Q4S4M4WDOFMYQH6J2CET25CYC7PR5Z2BO3CVBN7EHIYTMUXVG76AX6EN75DR5U5Z7FOP7JUO36RFWCD3PQAKLHXIZQ', 'https://www.citroen.hu/modellkinalat/szemelyautok/c3.html')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO citroen 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('C4 CACTUS', 'A C4 Cactus eredeti megoldásaival valósággal felpezsdíti a kompakt ötajtósok piacát. Egy tömbből faragott, letisztult sziluettjén visszaköszönnek a márkától megszokott különleges vizuális elemek, mint pl. az ajtók alsó részére átköltöztetett Airbump® betétek, a 360°-ban körbefutó ablakfelület, a „lebegő” tető, a két szinten elhelyezett első lámpák vagy a nagyméretű, 3D hatású ledes hátsó fényforrások. A C4 Cactus a 7 karosszériaszínnek és a rafinált színfoltokkal operáló négy színcsomagnak köszönhetően számos külső személyre szabási kombinációt kínál.', 'A clear, silhouette carved out of a block, the brand is back migrated to the bottom of the usual from a particular visual elements, such as. the doors Airbump® deposits, 360 ° wrap-around windows interface, the floating roof, the front lamps or large, 3-dimensional LED rear lights positioned on two levels. The C4 Cactus offers a variety of exterior customization combinations with 7 body colors and four color packs that use sophisticated color patches.', 'img/citroen/c4-cactus.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UDADMG52R4W5N2SL7YAU2NQTMJ4LFELN2ADKR726WHIBJMZ4WE5GOLTHFYDGIVKJI6IELKIFA2EI36IFA5WEJHVRYKFFBI6F6MDTNUQA5USQBEZ3TYTHYIX4RGRQMDWOCB5DCP6KJWKKJY6YACX234VJJFDIUMLE4BV44PGJQEW27M5YYONJCQW66U42VA4TNMV7QWYO7ESCRBTPXOKI26DQD4FIYCVLBZSWUFEMHEKY4246KER3TYFECX5FLOP5IA24EFNGIVOEXGOF6IWP4HHIYIFJPNTLNGHH424HQX5QYLIJUHKWB5LFM2UDMW4OPHL7AZ5RQQUYWXSDFVHNGTDVC2GJ7DGTRGGRTCHOE4ULMOY5TDRSEOVV4GFONMIY5Q4NHCBLVN5TCWKK3CYFNHIK7GRBM4LGJOE5DW3FUYGMVUVRMCLK7DW4DWNDZAUYAM3QUYUPLRC4HDLXWXWEDSLCWRF6JFZD3WSTWGXNNWZDPI6N4P4TEUPRFTITL2C374W47HGLR6J3H4BCZHLXZMIWCY6TKBUDPYTTRJ46GHA5WE6O6JM7LMMMH66SYCYREYJ5VTGOCTBC66PI6SOP6IMFBL2FMX3TGBQJIDLKNDE5FKDB5CQAWSRVJRFQPZSUTTTCXUCG3FMDQRVUG6SKPKZQXQHHIHPKWW4XXN3HPDHBQ3QLOEO3SOQQU6TMWQX34OOOQ3UY5IZ7SBUMJWKL2D77QN7CK76R464O47SZH7U3HNPI43BB574BL7FDU2I', 'https://www.citroen.hu/modellkinalat/szemelyautok/citroen-c4-cactus.html')";
    mysqli_query($connection, $query);

    $query = "INSERT INTO seat
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('Ibiza', 'Állítsa össze új sportos SEAT Ibiza modelljét FR felszereltségben. A 18 Performance keréktárcsákkal, panoráma üvegtetővel, dupla kipufogócsővel, fekete kárpitozással és kontraszt varrással minden apró részletében dinamikus külsőt kölcsönöz az új Ibizának.', 'Set up new sports with the SEAT Ibiza in FR. With 18 performance wheels, panoramic glass roof, double exhaust, black trim and contrast, every detail is dynamically exterior to new business ventures.', 'img/seat/ibiza.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2U2ZN3RTADF5RNHBBW6JWRKT4Z2QMB7HEBMDVFUUPUOCICJI2JSB5ZPMV5TEFS3X7RD3LQPDPECVEXXUCFVFCQNCE5XECUOHAED3YYFCTQQNFWNCX5ERIZUCWBMY3TYTBYZH4UNYYGAGNAQNZRH6FA3XHEUBMEB35NWKUUSBWKOETKA46JNTSMBHWX3HOGDZ7CAU62WM6VI5TBMJ7QO3L3WJKLAS6MREKBY63SDQFI6CRIWFHB3AZCWXBLTTISH6NBERK3KLGU32Q5ZYIM6MBJMHXS5CXD336DONLDY4IFR5FTAX76SZUTD5BGYYKL72ZKW4RSBXQXMP6V37B3IUYKKALL5BKZGXFLNEFDFDEWLPJRIIHRWMBQFS5KVXGEP4ORDV5HBRTTLKCE4HBFYQP5MNDE6JK3CIFNI2KTGBHMPQSYXSKRTN26MTEKSLYV5HXPRSOBL6R4QKMAGFYKEKHXEJ3PFL5GPLRG7HFZ4E5SJOE65UU5RV3HNWI3ZHPMT7MDZWPBBCO5A57LPH72ZT47ZGHZAMXRUNENK7RKCVKT55YGAN6KPORFTWZUG6JAT7T3D2D7DZ6HWJIIOH2OPRMZ3KMEDOTIHU4L7RL5JKQQFN7JOIEBNDNBIEOT4WIIGUOA2ZKCVGC6R6GCTZMMA7WQ3MVQWKGWRL2JB5JOMGPAPBSLKRZXYE7WQG5GW4OVMISH6I2GETY5KZBTXY6I6QLUY5ILPZB2GM2FF5JTP47H7ZD56UZY7GJ77EGH55IUL5HLJ7XYANEF3QVA', 'https://www.seat.hu/ibiza/ibiza')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO seat 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('Leon', 'A SEAT Leon ikonikus kialakítása megkülönböztető vonzerővel bír, mely bármely élethelyzethez  tökéletesen illik. Tágas tér áll rendelkezése, hogy az élet legjobb pillanatait korlátok nélkül élvezhesse.', 'The iconic design of the SEAT Leon has a distinctive appeal that fits perfectly into any living situation. Spacious space to enjoy the best moments of life without limits.', 'img/seat/leon.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UDAFE3N2R4W5N2SL7YAU2FQJ6F6BSSFW5BBRI77PDDUAUWN4WE5GOLTHFYDGIVKJPOIELKIFA2EK36IFA5WELHVRYKFDBICF6MBS5UQI5USQBEZ3TZTHYLH4QMI4GDYNARA6YD7SWMTWSGNWMBV2WXGKGII4FLAZ7BNLEOZJGBZ7LFTXPBCSIMHH7UXGVQGE7KBN45XDDYUQU4P3U3CQWHS4E6BKGQULQ4ZPKCQGLSFY4246KER3TYZEC72DH472ADFYIC6MBK4JPE4LMTM7Y2PIIYFKPNTI5GEX424HQX5QYHIJUHKWB5LFM2WHM455MZP4CH5GSCTCZ6ANGVVJE26FPLFLFWLPJTIAGRWMRSFS4KTXSHRJRKFO3W4CBWNNAZ5W4FHCBOK33GLM4UWFQK26YU6JCCZ7OFS4JKHNXLJUMZJJLDXUOV4HNYDO2XQBBQA2XRJRA64RH55VLVL3RB5FBNE25E25ZZ3BK3HKWI34TXWO6ZHOYH7MOACM52G26QO77VXHZZS4PSMZ7BISJ256DCFSWHV2QMA36U64CPHVRIE5ZATXS3H2T5DR7HUWAWEPGSPNMZTQUYKQPT2HUCL7SDBIKORJF6S5QMAKA32XIZFJKRYLIEAFUUNKMY4D6NVAS42R5MRSZLC4UNNGXUQT2WMB6B32L2GRUXFN37ZDYJYMK4K7RHU4TVE5HG3F4F67DDTUG4GHKCP4RNDGNCS6U27YDP2S77UOHGRXH5WN75GZ3H2AWYIPH6ANMHJ2MY', 'https://www.seat.hu/leon/leon')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO seat 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('Ateca', 'A SEAT Ateca mindennel felszerelt, amitől a napi rutin kényelmes és élménnyel teli lehet. A Full Link technológia segítségével nem kell lemondani utazás közben sem az okostelefonja által nyújtott alkalmazásokról, a vezeték nélküli mobiltelefon töltővel mindig elérhető maradhat.', 'The SEAT Ateca is equipped with everything you need to make your daily routine comfortable and enjoyable. With Full Link technology, you dont have to give up on the apps on your smartphone while traveling, and you can always stay connected with your wireless cell phone charger.', 'img/seat/ateca.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UDADEW52R4W5N2SL7YAU2FQJ6F6BSSFW5BBRI77PDDUAUWN4WE5GOLTHFYDGIVKJPOIELKIFA2EK36IFA5WELHVRYKFDBICF6MBS5UQI5USQBEZ3TZTHYLH4QMI4GDYNARA6YD7SWMTWSGNWMBV2WXGKGII4FLAZ7BNLEOZJGBZ7LFTXPBCSIMHH7UXGVQGE7KBN45XDDYUQU4P3V3CQWHS4E6BKGQULQ4ZPKCQGLSFY4246KER3TYZEC72DH472ADFYIC6MBK4JPE4LMTM7Y2PIIYFKPNTI5GEX424HQX5QYHIJUHKWB5LFM2WHMY55MZP4CH5GSCTCZ6ANGVVJE26FPLFLFWJ7DEQINDIZTHXCPXHN63XWECQKNLNILC42KXTLAZ6WUE7FRWMTZH3MMCVV5LK4YE5ROKJZ6TUMLKXLHZKUCYFIL534OZQG5UDGSXABROCSSR5WALXONK5DA4MRJILBGXNGHMOOZKWZKXSO6EZ5TXWJ3WF73BQJDHKRWXULX7ZNZ6OMXL4TWPYCNSOXPSZBMVR5OUDAG7RHHCTZ4MOBXMIE54SZ6W7I4P55FSFRCZQ33LGM5FGCED46V5ES74JUFBJ2FEX2LWBQBIDPK5DEVFKHBNAQAWSRVJTDRPZWUCLTCXUCGLFMLSRVU26SCPKZQXYHPJPI2GS4VXP7EPBHBRLRL6E6TSOUTU43MXQX34MOOQ3QY5IJ7SFUMZUKL2T57AN7KN76RY42G47W2X7U3HM7IC3BB47YB5M4XKBI', 'https://www.seat.hu/ateca/ateca')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO seat 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('Alhambra', 'A SEAT Alhambra kialakításának köszönhetően messze kitűnik kategóriájában. Családi autó, mely nem csupán kényelmes és praktikus, de stílusos és egyedi megjelenésű is. A tágas helykínálat, a technológia megoldások és a szórakoztató funkciók minden családtag elégedettségét garantálják. A hétvégi családi kirándulástól a gyerekek iskolába szállításáig a SEAT Alhambra minden kalandra és feladatra ideális társ.', 'Thanks to the design of the SEAT Alhambra, it excels in its class. A family car that is not only comfortable and practical, but also stylish and unique in appearance. Spacious space, technology, and fun features guarantee the satisfaction of every family member. From weekend family outings to transporting children to school, the SEAT Alhambra is the ideal companion for all adventures and activities.', 'img/seat/alhambra.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UDAFEXN2R4W5N2SL7YAU2FQJ6F6BSSFW5BBRI77PDDUAUWN4WE5GOLTHFYDGIVKJPOIELKIFA2EK36IFA5WELHVRYKFDBICF6MBS5UQI5USQBEZ3TZTHYLH4QMI4GDYNARA6YD7SWMTWSGNWMBV2WXGKGII4FLAZ7BNLEOZJGBZ7LFTXPBCSIMHH7UXGVQGE7KBN45XDDYUQU4P3U3CQWHS4E6BKGQULQ4ZPKCQGLSFY4246KER3TYZEC72DH472ADFYIC6MBK4JPE4LMTM7Y2PIIYFKPNTI5GEX424HQX5QYHIJUHKWB5LFM2WHMPU66MX6BT6TBBJRMPAG3K2USNPC7VSRSLE7ZTIAGRWMRSFS4KTXTWMOFIR263QQFZVVDDWDTU4IF7LHMZFSCWY6BLL2SVZUJLD4ISLZHIZW5PGJSFJF4K6R3XY5HAN3I6MFGADC4FGFD3SE5XSV6TPWGHUUFSTDWTHWHFMVLMRLZHPKN6Z3LFOPVA4NTZIJTXILH3Z576WMXH6LROIDF4NHJTIX4NQVKU7HGBQHPCT34IMZWNAD5ESJ6XPPMP4NHQ5SSDQT4KKN5TGKCDA2B7HK64I72IUEBJ3VGWCIWRSRECHJ5LEFDKHANMRA2TBXJ7DAJYWWCPTKNUKALFPLYR5U26RSBLRWHQG7FPAZGO7VZOHGPBHBXKJN6E5DWP4WUMZMXQ744APOQ2Q35ELPYFMMZUK36S36AV72D76UYY3GS76ZXPV3BNXKC3DRS7MN5OTHA', 'https://www.seat.hu/alhambra/alhambra')";
    mysqli_query($connection, $query);

    $query = "INSERT INTO nissan 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('Micra', 'Ebben a közel 4 méterben, a lebegő tetővonaltól a rejtett hátsó atjókilincsekig a Nissan Micra ötvözi a merész formatervet az 5 ajtós csapotthátú kialakítás sokoldalúságával. Cinkostárs a városban.', 'Within this nearly 4 meters, from the floating roofline to the hidden tailgate, the Nissan Micra combines bold design with the versatility of a 5-door hatchback design.', 'img/nissan/micra.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2U2ZR3NTADF5RNHBAZ3JM2KM6FQF7KJSWGGMQR3BILIMWQMJGBFZPMU5W5JNZ76BD33RPHOEA3RW6IMWJNMWIJB4JFV4QIRXNYWALASUK6FAIVZYOFFJQ63FFABJDWHSG7SR72GBCQYHM4EA64JYZHKZRJDD3CAK7LLSHHEUUCVRMTQHHTXMUTAOJ2ZC534B3EODU35FZVMBRH2RLPCN4KQGJFMZXUKC26DQD4FIYCQLOKOTWBCDN2AXHHITPI2BPDFUUCTE52JXLQRVYYKUYDNBWFWFXX7TTU4IKUJTN23BB37NHTZCHWDGIYWI7WZ2V5NKD7CNW4VMH6BW7BQQUYWHQDNVHKHTD353NS6DGTTHGRTCIWDPWV5NXCZBESVFWCSXGSFT2YGHJVBPYZSDCNJWZCHVNLK2SWBGMIGQ2H2KRTNC4MYVKSIYV5JGHYZHA53IZMFGADG4FCFAHSE5PSVODHFYTNURKPFGNSXQO64T5XGWA35TXUOWZHWKROGQ3DYSLWFT56JPPWLFY6MLTSA7OTF24ZB3DMHIFEMQZ6EV4KPHRRQG5WBXJFWPV3HX57HZR4WMJXUXCOXUMZYK4GQ7TXXUDT7SDBIK2SUM6OKYGGFAM5PUMQU5I4BSKACOKGRG6F6TSNMH7GPLKUIWC2XBD3JN5OM4GPALBS32EZX7EXUDX5OQ4TXN2QT4I6HC5ZFJFVRHQ7Y4QHXI5ILOZC3WA3FBNA7TYPZ74Z77INMMTMP7SF35ESFS5ZSTP76QLUNWOCBQ', 'https://www.nissan.hu/jarmuvek/uj/micra.html')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO nissan 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('370z', 'A 370Z meghajtásáról a negyedik generációs VQ V6 motor gondoskodik. A 3,7 literes hengerűrtartalomba rejtett nyers erővel a 328 lóerős, változó szelepműködés-időzítésű és –emelésű (VVEL) technológia folyamatosan finomítja a szelepek emelkedését és időzítését így csökkenti az autó reakcióidejét és növeli a nyomatékot, mindezt az üzemanyag-hatékonyság optimalizálása és a károsanyag-kibocsátás csökkentése mellett. Lenyűgözően hangzik? Tegye próbára! Az alapjáratról eljutni a 7500-as fordulatszám határáig – akár egyenes szakaszon, akár kanyarogva – maga a csoda.', 'The 370Z is powered by a fourth-generation VQ V6 engine. With a horsepower in the 3.7-liter displacement, the 328-horsepower Variable Valve Timing and Raising (VVEL) technology continuously refines valve lift and timing to reduce car response time the torque, all while optimizing fuel efficiency and reducing emissions. Sounds amazing?', 'img/nissan/370z.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VCZR3RDAEF5RNHUAASMJ6N46GNVGQ7VYIJKTIRBQL4FXRCE2EDXT5ZJEYPCGRPSTPKXZOV4KANZL3FXXECVFWCYNCBNPECXX3GER2YUVCWQUNCXHAYUNGADMUUAFEO7OE36K37IQEKDA5DQRPOYDXSGUSWSGFWMAN2WXGOGIJMFLAZPANLHWZJGB4SNCG3X6RPEWBTX3LXKYDCOMAW6UYQY6FGV6B6ZHIQFB7XFHAKR4GCUHHJ3AVB64BOHGUH6RUM4GHJAX6WZHF64AJOCAUTELXGLRFC7ELH6DRU4FKRHG3VWSDX65ODQK6YMZHCJA25QXJ5DKFH3XEOPHL7AJ5RQQUYWXSDEMHNHTD3W2NW6DGTSGGRTCGWLPKVKQHRJBKFOFFONALHWQIOTOCXRYXDJ4TFRGHLKWVNHMKMYQNM47BYGFVDWTGU2BCSUVQ37DUMBXNAVWVQAMPQEUUPMIBXOKXMN4422YQOJNK2OW3GXUO6455T2WQ35TXUMG2374YDDZWRUJV5CJ77FXHZFK7PCMZ7AHWJW56DAFQWHUSQGAN7KPOBHT2YUDW4TZ3ZNT5J6RQ736KYLCGTIWWSNZYKEFL7Z432BZ7ZBQUFHIUS7OOYGEFAN5LUMSUTI4BQKACGKGVGOF63SNIHPGTLLUMWCYXBD3JV5MU2UDDPAN6SO6WNNZLM3OM6CODGXQX4I4HE5ZFJVWZHB7VYQ45BXBTGYS7ALYYLIVXWGT4AT7UX75BRRYNZ75TP7JGJMXKM3BR27RR7HJHI', 'https://www.nissan.hu/jarmuvek/uj/370z.html')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO nissan 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('GT-R', 'A Nissan 3,8 literes, V6-os, 24 szelepes, iker-turbófeltöltős motorja – amelyek mindegyikét saját takumi szerelő készíti kézzel – alkotja továbbra is a Nissan GT-R hajtásláncának szívét. A kifinomult Nissan GT-R Nismo a versenypályán fogant technológiákat és szakértelmet sűríti magába. Az új Nissan GT-R Nismo élesebb teljesítménygörbét kapott. Exkluzív turbófeltöltő-kialakítással büszkélkedhet – közvetlenül a GT-R GT3 versenyautóból átvéve – módosított formájú turbinával és kevesebb lapáttal. Ez optimalizálja az áramlási sebességet és 20%-kal javítja a gázadásra adott reakciót, mindezt egyetlen lóerő veszteség nélkül.', 'Nissans 3.8-liter, V6, 24-valve twin-turbocharged engine, all hand-crafted by its own tailor, remains the heart of the Nissan GT-R. The sophisticated Nissan GT-R Nismo combines racing technology and expertise. The new Nissan GT-R Nismo has a sharper performance curve. Featuring an exclusive turbocharger design, taken directly from the GT-R GT3 racing car, it has a modified turbine design and fewer blades. It optimizes flow and improves gas response by 20% without loss of horsepower.', 'img/nissan/gtr.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VC3V3NDAEG5RNLUAAUUMI7FWXNJH5WCCGROSNQPYGDEHPIQLRG6HNHFEGXH4YV2G47GOHTODAC4V7STHSFCSRBEHREGXSBCG5XCYBMCCRLYUBCXHBZWKIHW3JAASM5R4R74UL6BSI4GB3HBAHXCOCJKWMKJY6YACX2Z4VJJFFIUMLHMBV4U3FFIDLNPWK4OGEURYLPPLONKAMJ2WK3Y3P3HTJBI7LXU5CQGHS4E6BKGQUCYOMTVBKDNYAWHGVH6RUK4GDJAF7POTQ7OAGXBBKRSF3VFM2ITZCZ7M4NLDYUNJV5JVAX77JQ4CHSDNNREQNKYLW46VC75TSH7SV7Q6UIMFFAFV6QVFZZRM27U3RU6OE5KGMJDYF5IXVLOF6DJBKDONW4KFGPNAU5W4FHCYLDN4TFWGHLKWVNHMKPIQNOUPQ4DC2R3Z6KFCWJK23N7FUMBXNBZGVYAMPQEMUI4IBXOKUYN47K26QOJMKYMWZEXQO6U55T2WA34TXQMGZH6LROGTJDYTLSB375G67PGLR7JXHEB65GLVYUDWEYOXKJVDDYDXRJ56GGA3WQH5ESJ6XM77X4NHO5SCBQ3ZKGV5BGCCPBU36OJ5YR7URIIC2XVGUCQWRWRUCHJ4LEFBJHANMVAKTB3I7C7JZGWDPTJNWKILGLLIR5UW6VSBL65WQG7VGDSM57PUYOM6CODNUTL4I2HC7ZNIZCZPB7ZYA65DVBVLE3PYDMEZULO7AM7AI75R67IM4PTYP7E3H5NIU3RD5X2BOSVI5FG', 'https://www.nissan.hu/jarmuvek/uj/gt-r.html')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO nissan 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('Navara', 'A bátor Nissan pickupok 80 éves történelmét tekintve a Nissan Navara marcona kinézete nem a véletlen műve. A magas megközelítési és elhagyási rámpaszögeknek, valamint a megemelt hasmagasságnak köszönhetően a Navara megjelenése egyszerre kelti egy erőteljes és belevaló 4x4-es benyomását, és nyűgöz le friss és modern megjelenésével, amelyet az elegáns, aerodinamikus formák és a jellegzetes fénymintázatú LED lámpák kölcsönöznek neki.', 'With 80 years of brave Nissan pickups, the look of the Nissan Navara marcona is no accident. Thanks to its high approach and departure ramps and elevated height, the Navaras appearance gives it a powerful and immersive 4x4 feel and impresses with its fresh and modern look, thanks to its elegant, aerodynamic shapes and distinctive LED design.', 'img/nissan/navara.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VCZR3RDAEF5RNHUAEUYN3GOPDCGTIP24EAVJUIYZF2CWYJTKQO4PXFETGUO2N6KL5C6FWXRMB3EKXEXXECFFGCYNCANPECXX3GER2YUFCWQUNCXHAZW2IAK3JIASM564J74VT6BCI4GB2HBA6VRHPENLFFEMPMIBL5NOIU4SSQKWFSOA46ONSSMBVWXLHOP4FMRYKPPLONKAMJ6WC3Y3MHHTJBIQ3XZWFANPBYB6CUMBIXRZSWUFEMHELZYVZ4UBD7GRSIV5UGPZ3US6XBCLRQFFRF5TRMCJT7C36ISNLDYMKZZ5ZXAK47SZWDDNBGQZKIGVMVVOQ5R67SZQ7YHP4NEHGFS4A25J2RYYVWDPSOYGJHEONDGEJMG7ML236FDCJFKNMNS42AWPPAY4G4F7BRGGTZG3MMOXVNKKMYU7RA2JZ6DQMLKXPGJIUKZFLLNX4WRQG5UDE2XABR6ASSR5RAG5ZC5RXTTLLCBZFRLJS3ES6RV2JN3DLWXLMWXUPGVG6NQKHYSRUJV5BN77I6PTTFW7EZT6CPETV34GALBMPNVAYB75JFYE6PLCQO3SNHPFWPVH2GD7PJLBMI2NC22JXHBIQVP7HTPIHH7EWCQU5CST5Z3AYAUBXVORSKSVDQWAIALJI2UZS7X4XKBZZU32ZDFSWFYI22NPJBHVMYLYDPUTXVDLOK3G7TXQTQYVYF7CHJZHKJ2OJWLYL56GHHINYMOUE7ZA2GM2FF5RU7QG7VE37UGGHBXH7WD75GRLJ2DGYMP76UBO5FH', 'https://www.nissan.hu/jarmuvek/uj/navara/formaterv.html')";
    mysqli_query($connection, $query);

    $query = "INSERT INTO audi 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('A5 Coupé', 'Az Audi A5 Coupé sportossága mély benyomást kelt - már az első utazástól, mégpedig az elegáns háromajtós modell széles légbeömlő nyílások és krómozott díszlécek jellemezte, új formai nyelvezetének köszönhetően, amelyek sportos karaktert kölcsönöznek elejének. Oldalán markáns küszöbborítás fokozza sportosságát, az extrafelszerelésként rendelhető, 20 col peremátmérőjű alumíniumöntvény keréktárcsákat pedig a kidomborodó kerékjáratok emelik ki. A far szélességét a diffúzor matt Alumíniumezüst keresztirányú díszléce és a trapézalakú kipufogóvégcsövek hangsúlyozzák. További egyéni kialakítási lehetőségeket kínálnak az Audi A5 Coupé számára az advanced és az S line dizájncsomagok. Az itt bemutatott modell az edition one, az Audi A5 Coupé exkluzív felszereltségű, különösen sportos kivitele.', 'The sportiness of the Audi A5 Coupé is deeply impressed - from the very first ride, the stylish three-door model features wide air vents and chrome moldings with a new design language that gives it a sporty character. On the side, a pronounced sill trim enhances the sportiness, while the optional 20-inch aluminum alloy wheels are highlighted by the bulging wheel arches. The width of the tail is emphasized by the diffuser matte aluminum silver transverse moldings and the trapezoidal exhaust manifolds. The Audi A5 Coupé offers additional custom design options with the advanced and S line design packages. The model presented here is the edition one, the exclusive sporty version of the Audi A5 Coupé.', 'img/audi/a5.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UDAFE3N2R4W2V5JFX4AKNS2ATRPSMMQN3ISMUP7PTDUAUWN4WE5GOLTHFYDGIVKJPOIELKIFA2EJ36IFA4OEIHVRYKFHBQYLM2FP2JAR3JFICJTXHRGHRSPZA2RQMAM2BA3TCP6KJWOOJYCYACX234VJJFDIUMLG4BZ4S3FEYDPNPWO4MGKZCQU66W42VA4TNMZ7QWYP7GSCRRTPTOKJ26DQD4FAYCVPDRFFJKMYOIXTQLTZYQHWNBER33IE7TXJR6OCHHDB2ZCD3NFMSJT7CN5BTGVR4WFCU6S7QL47SZWDD5BGQZKIGVMVTOY5RT7VTD7YKX2OUFGFS4A25JKUZMOFDEGPPRRJYHRWMITC4JJQSKNCFJFZ6TTI2ZVUCAP3QT4OFYKPEZNRQS2V5LIDCT2ECLND4G4YWVO6OSRIVSKUW3PZ43AN3IKLVOADD4BBFD3CB53SF2TOXGVXEDSLCWLFWJF4TLUS3XGXMNWZLPE55CP5QOGZ4QYJ3UDT55677LGLT7FUXEBS6GPUZV36FYKVKPXTAYDXRJ56EGM3GQ35ESN6HNPMP4NH47SSCQT42ANVTGOCXBU34OJ5IT74QIICWVVPHCIWBQRMDHJ5LEFDKHANMRASSBXJ7G6JZWWCPTJFVKELFNLQR5US6TSJKRRHQH7NAN2NNY5KYOI6CODEXSX4ICHE5ZBJZOZPB7VYQ45CXBR2UXPQDMMZUK36TX6AN72D76QYY3G676VX7V2BNXKC3BRYXHF2XIXI', 'https://wwww.audi.hu/a5/uj-a5-coupe/attekintes')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO audi 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('Q5', 'Szinte mindenfajta útra és talajra készen áll, akárcsak a jövő kihívásaira - a quattro összkerékhajtás az ultra technikával. A quattro állandó összkerékhajtáshoz csatlakozó mindegyik négyhengeres motorban intelligens üzemi stratégia gondoskodik arról, hogy az Ön Q5 modellje is mindenkor gazdaságosan, dinamikusan és biztonságosan közlekedhessen, mégpedig a jól megszokott, rendkívül hatékony vonóerő-átadási képességek mellett.', 'Ready for almost any road and ground, just like the challenges of the future - quattro all-wheel drive with ultra technology. All four-cylinder engines connected to the quattro permanent all-wheel drive feature an intelligent operating strategy to ensure that your Q5 is always economically, dynamically and safely driven with its well-established, highly efficient traction transmission capabilities.', 'img/audi/q5.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UDAFEXN2R4W5N2SL7YAU2NQDOF6BSSFW5BBRI77PDDUAUWN4WE5GOLTHFYDGIVKJPOIELKIFA2EK36IFA5WELHVRYKFDBICF6MBS5UQI5USQBEZ3TZTHYLH4RGRQMHWOCADDCP6KJWOKJZ6YACX234VJJFDIUMLG4BV4S3FEYDHNPWO4MGKZCQU66W42VA4TNMF7QWYN7GSCRRTPTOKK26DQD4FIYCVPDRFFJKMYOIXTQLTZYQHWNDER33IE7TXJQOXBCLRQFNRF5GQWJEZ7R45CDGVR4WFCU6S7QL47SZWDD5BGAZKIGVMVTOY5R672ZQ7YF35GCCTCZ6ANGU5M2MOFDEGJ7DGTRGGRTCMKRHG3XGFCUI5PNYIC422RN3BZZ6EC7FTWMSZALMO4VV5JK42EVQQWDO4J2HNXLJQMZLJLCXEO56HFYDO2HSBJQA2XBJRI64RHN5VLULXRRNFBME25UY5RZ3FK3FK6J3YTHWO6ZHOYX7MGBMM4KG26RO77FXHZZS6PSMZ7AGWJ256K6FSWHV2QMA36E44KPHRRYG5RATXSLH235DR7XUVQWELGAPNMZTUUYIQPTZHUSL7SDBIK2QUK7JOYGAFAN5LUMSUVI4FUCAC2KGVGMPZ7F2QJONE6WIZMVROKGWTL2IJ5LGA7A35F5DI2LSW574R4E4GFOFPYT2OJ2SOTTNS6C7PRRZ2DODDVIM7ALYZTIVXVGP4A37UP75BRRUN575PP7JWKZOQFWDD57I47XIYQ', 'https://wwww.audi.hu/q5/q5-1/attekintes')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO audi 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('TT Coupé', 'Az Audi TT Coupé már alapkivitelében az Audi drive select menetdinamikai szabályozórendszerrel készül, a vezetés élményének igazán vonzó palettáját kínálva. Az Audi TT Coupé futóművének különlegességei közé tartozik progresszív kormányzása, négykaros hátsó felfüggesztései és elektronikus menetstabilizáló rendszere (ESC). A kerekenkénti forgatónyomaték-szabályzás a gyors kanyarokban lép működésbe, a belső íven gördülő, s ekkor lecsökkenő terhelésű kerekek szükség szerinti fékezési beavatkozásaival javítva az irányíthatósági tulajdonságokat. A hétfokozatú S tronic sebességváltó szintén hozzájárul a sportos menetteljesítményekhez.', 'Already standard on the Audi TT Coupé, the Audi drive select has a Dynamic Drive Control system, providing a truly attractive palette of driving experience. Special features of the Audi TT Coupé chassis include progressive steering, four-link rear suspensions and Electronic Stability Program (ESC). The torque control per wheel is activated in fast corners, with improved braking action, as required, by braking action on wheels that are rolling on the inner curve and then decreasing load. The seven-speed S tronic transmission also contributes to sporty driving performance.', 'img/audi/tt.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57UCICJW7VTZNVK2SL7YAU2FQJ6F6BSSFW5BBRI767GHIBJMZ4WE5GOLTHFYDGI5VLD5ARMJIUTIRDMZAVTQYRHB2GBKUUEDYWZUO5USEDGQJYFTDOPCOHBC7SWXDAYHKUCD5HCOCJJWKKJY6YACX2Z4VJJFDIUMLE4BZ443FFYDLNPWK4OGGURYJPPLONKAMJ2WK3Y3MHHTJBIQ3XZWFANPBYB6CUMBIVQ4ZPKCQGLSFMONOPNBI5ZMCSBL6WVHH6YC24EFNGIVOEXGOF6IWP4VVU4FCQXG3VWSDX65ODQK6YMVWESDVLAOXSWMKHWOM46MX6BT7DRBJRMPAGZLKVHTCREZRR34NKKGMITWFG4IIE5EORLVNPBRJTLCFXMXBHYQKYLPMY5TQSYVZLJ3CTZEKLHBZV3RFI5WZNGRTFFFMO4SZXQ5XA5TK6AEGADG6FOEADSF4PWVPFOMEFUUFVDLUTLWHHNNWZLPI55JP3G5NHX4LYGJA6HOBA5PIDP7W3T44ZOH5G45QDLEZO7DPKYLD2NIGQM7CO6FHTYYYDG2TZ2ZFT5PRZQ732KYLCETAHGUMZZKMEL3ZUT2NZ7ZBYUFLIFS7OOYGBFCNFIUMTUXIMCSOASYKGVGAWZ7F2TOOME6WQ3MVQ6CGWR32JJ5LGC6A2NA55K27SO5XM44M4WDOBNYR36J2CCT2NCYC7PR5Z2BO3DVDHOIGZQGZJ7INX6BP4I37SHT7R3R6K576TI7VVCTMEXW7QBHF3XIXI', 'https://wwww.audi.hu/tt/tt-coupe/attekintes')";
    mysqli_query($connection, $query);
    $query = "INSERT INTO audi 
              (model, leiras, leiras_angol, kep_src, hasznalt_link, uj_link)
              VALUES
              ('RS 3 Sportback', 'A világ legerősebb, 294 kW (400 LE) teljesítményű és 480 newtonméter maximális forgatónyomatékú, sorozatgyártású öthengeres aggregátjának köszönhetően az Audi RS 3 Sportback álló helyzetből mindössze 4,1 másodperc alatt gyorsít fel 100 kilométer/órás tempóra - és még elődjénél is 33 lóerővel többet produkál. Külsején az Audi RS 3 Sportback az elejét meghatározó, fényes méhsejt-mintázatú betéttel készült Audi Singleframe hűtőráccsal, nagyméretű légbeömlő nyílásaival és szögletes küszöbborításaival juttatja kifejezésre hatalmas erejét.', 'Powered by the worlds most powerful, 294 kW (400 hp) and 480 Newton meters maximum torque, the 5-cylinder mass production unit accelerates the Audi RS 3 Sportback to 100 km / h in just 4.1 seconds - 33 bhp more than its predecessor . Externally, the Audi RS 3 Sportback exemplifies the power of the Audi Singleframe radiator grille, featuring a glossy honeycomb pattern insert, large air intakes and angled sills.', 'img/audi/rs3.png', 'https://www.hasznaltauto.hu/talalatilista/PDNG2VG3R2NTAEH5C57QCEFS3M5I7LKW5JFX4AKNGYJ6F6BSSFW5BBRI77PDDUAUWN4WE5GOLTHFYDGIZVDN5AZMFMUTIRDMZEV5QYZPO2GJKUUEAEWZUG3USFDKRFQCJTXLRH7RWPZEPDAYPI4EEGGE5YQIWOKJZ6YADX2Y4VJJEQQKWFTOA26JNSS4BTRXLHOP4FMRYKPPLONKAMJZWC3Y3OGXTJBIY7X3WFBNPBYJ6CUMBIXRZKWUFEMHELZYVZ4UBD7GRSIV5UGPZ3UQGLQRFYYCXYS6JYWJEZ7R45EDGVR6WFCU6S7QL47SZWDD5BGAZKIGVOVYVMOYR72ZQ7YFP6NEFGFS4A2TJ2RYY6KFKMT6GJHEONDGEZMG77KW2RRAVCPK3KCQXGWVL2YOORRBX3MNRE6JG3DHVNPKKXGBHMMGCMPU5DG2VYZWKVEWRL2XM7DU4BXNBZQVYAMLQUQUHOIFW6KX2N4Y222QWKOOYKWZ2VSG7EV5THWDVWPVMRX4L3WBY2DEPCNOIXP7S3354ZOH5G44QH3UZOXBQOY3B2VJGMMPAO6FHXYYYDO2QF2JFT5O65Y7Z2K5LGEDAX2UGE5VGCED42N5GS74JUFBL2FEX2LGBSJIDLKNDE5F2DAMCQAWSRVJRDXPZOUSLTBXVWG3FMDSRVUK6SKPKZQXYG7IPM2WQ4VXP3E7DHBQLRL6E63SOQTE63MWQX34OOOQ3UYDIJ7SFUMJWKL2T57AN7CI76RY62O47SYH7U3HM7IS3BB57YBH3FLUTA', 'https://wwww.audi.hu/a3/rs-3-sportback-1/attekintes')";
    $result = mysqli_query($connection, $query);

    if(!$result)
    {
        die("Connection failed: " . mysqli_connect_error($connection));
    } 
    
    echo "Sikeresen feltöltötte az adatbázist teszt adatokkal!";
}
else
{
    echo "Már feltöltötte az adatbázist adatokkal!";
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adatbázis feltöltése</title>
</head>
<body>
    <a href="auto.php">Ide</a> kattintva átmehet a főoldalra!
</body>
</html>